name: CMake

on:
 push:
   tags:
     - v1.**

jobs: 
 build_packages_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v3

  - name: Configure Solver
    run: cmake ${{github.workspace}}/solver_application/ -B ${{github.workspace}}/solver_application/build

  - name: Build Solver
    run: cmake --build ${{github.workspace}}/solver_application/build

  - name: Build package
    run: cmake --build ${{github.workspace}}/solver_application/build --target package

  - name: Build source package
    run: cmake --build ${{github.workspace}}/solver_application/build --target package_source
